version: '2.2'
services:
  es-master-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es-master-01
    environment:
      - node.name=es-master-01
      - cluster.name=es-siem-cluster
      - discovery.seed_hosts=es-master-02,es-master-03
      - cluster.initial_master_nodes=es-master-01,es-master-02,es-master-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es-master-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es-master-02
    environment:
      - node.name=es-master-02
      - cluster.name=es-siem-cluster
      - discovery.seed_hosts=es-master-01,es-master-03
      - cluster.initial_master_nodes=es-master-01,es-master-02,es-master-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  es-master-03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es-master-03
    environment:
      - node.name=es-master-03
      - cluster.name=es-siem-cluster
      - discovery.seed_hosts=es-master-01,es-master-02
      - cluster.initial_master_nodes=es-master-01,es-master-02,es-master-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic

  kibana-01:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana-01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es-master-01:9200
      ELASTICSEARCH_HOSTS: http://es-master-01:9200
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: ps5U8MotSNqDlUONnyrR
    networks:
      - elastic
  logstash-01:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    container_name: logstash-01
    ports:
      - 5401:5401
      - 5402:5402
      - 5403:5403
      - 5404:5404
      - 5405:5405
      - 5406:5406
      - 5407:5407
      - 5408:5408
      - 5409:5409
      - 5410:5410
      - 5411:5411
    environment:
      ELASTICSEARCH_URL: http://es-master-01:9200
      ELASTICSEARCH_HOSTS: http://es-master-01:9200
      ELASTICSEARCH_USERNAME: logstash
      ELASTICSEARCH_PASSWORD: ps5U8MotSNqDlUONnyrR
#    volumes:
#      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
#      - ./logstash/conf.d/:/usr/share/logstash/config/
    networks:
      - elastic

volumes:
  data-01:
    driver: local
  data-02:
    driver: local
  data-03:
    driver: local

networks:
  elastic:
    driver: bridge
