---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
node.name: logstash-01
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://es-master-01:9200" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: ${ELASTIC_USER}
xpack.monitoring.elasticsearch.password: ${ELASTIC_PASS}

#xpack.management.enabled: true
#xpack.management.elasticsearch.hosts: "http://es-master-01:9200/"
#xpack.management.elasticsearch.username: elastic
#xpack.management.elasticsearch.password: 315gSxdXU54TkifhEV8h
#xpack.management.logstash.poll_interval: 5s
#xpack.management.pipeline.id: ["twitter", "beats"]
